export const REQUEST_DATA = 'SPACE/SPACEMISSIONS/REQUEST_DATA';
export const REQUEST_DATA_SUCCESS =
  'SPACE/SPACEMISSIONS/REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_ERROR = 'SPACE/SPACEMISSIONS/REQUEST_DATA_ERROR';
