export const REQUEST_DATA = 'DELOITTE/SPACEMISSIONS/REQUEST_DATA';
export const REQUEST_DATA_SUCCESS =
  'DELOITTE/SPACEMISSIONS/REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_ERROR = 'DELOITTE/SPACEMISSIONS/REQUEST_DATA_ERROR';
